### PR TITLE
WIP: Performance benchmarks

### PR DESCRIPTION
**Pull request by floswald**
hi @davidanthoff i need a bit of guidance here. i'm unable to run `query` commands when placed inside a module for some reason. In this PR there's a module `QueryPerf`. if i call the runner

```julia
julia> QueryPerf.run_benches()
ERROR: 
Stacktrace:
 [1] DataFrames.DataFrame(::Query.EnumerableSelect{DataValues.DataValue{Int64},Query.EnumerableGroupBySimple{Query.Grouping{DataValues.DataValue{String},NamedTuples._NT_id1_id2_id3_id4_id5_id6_v1_v2_v3{DataValues.DataValue{String},DataValues.DataValue{String},DataValues.DataValue{String},DataValues.DataValue{Int64},DataValues.DataValue{Int64},DataValues.DataValue{Float64},DataValues.DataValue{Int64},DataValues.DataValue{Int64},DataValues.DataValue{Float64}}},DataValues.DataValue{String},NamedTuples._NT_id1_id2_id3_id4_id5_id6_v1_v2_v3{DataValues.DataValue{String},DataValues.DataValue{String},DataValues.DataValue{String},DataValues.DataValue{Int64},DataValues.DataValue{Int64},DataValues.DataValue{Float64},DataValues.DataValue{Int64},DataValues.DataValue{Int64},DataValues.DataValue{Float64}},Query.EnumerableIterable{NamedTuples._NT_id1_id2_id3_id4_id5_id6_v1_v2_v3{DataValues.DataValue{String},DataValues.DataValue{String},DataValues.DataValue{String},DataValues.DataValue{Int64},DataValues.DataValue{Int64},DataValues.DataValue{Float64},DataValues.DataValue{Int64},DataValues.DataValue{Int64},DataValues.DataValue{Float64}},IterableTables.DataFrameIterator{NamedTuples._NT_id1_id2_id3_id4_id5_id6_v1_v2_v3{DataValues.DataValue{String},DataValues.DataValue{String},DataValues.DataValue{String},DataValues.DataValue{Int64},DataValues.DataValue{Int64},DataValues.DataValue{Float64},DataValues.DataValue{Int64},DataValues.DataValue{Int64},DataValues.DataValue{Float64}},Tuple{DataArrays.DataArray{String,1},DataArrays.DataArray{String,1},DataArrays.DataArray{String,1},DataArrays.DataArray{Int64,1},DataArrays.DataArray{Int64,1},DataArrays.DataArray{Float64,1},DataArrays.DataArray{Int64,1},DataArrays.DataArray{Int64,1},DataArrays.DataArray{Float64,1}}}},QueryPerf.##7#10},QueryPerf.##8#11}) at /Users/florian.oswald/.julia/v0.6/IterableTables/src/integrations/dataframes.jl:126
 [2] bench1(::DataFrames.DataFrame) at /Users/florian.oswald/.julia/v0.6/Query/perf/Rdatatable.jl:63
 [3] run_benches(::Int64, ::Int64) at /Users/florian.oswald/.julia/v0.6/Query/perf/Rdatatable.jl:75
 [4] run_benches() at /Users/florian.oswald/.julia/v0.6/Query/perf/Rdatatable.jl:73
```

the odd thing is if I do the functions step by step in the REPL it works:

```julia
julia> df = QueryPerf.createData(100,10)   # create the BM data
julia> using Query, DataFrames
# this would be the body of `bench1` as called by `run_benches`:
julia>         t1 = @from i in df begin
                        @group i by i.id1 into g
                        @select {r=sum(g..v1)}
                        @collect DataFrame 
                   end
10×1 DataFrames.DataFrame
│ Row │ r  │
├─────┼────┤
│ 1   │ 32 │
│ 2   │ 34 │
│ 3   │ 14 │
│ 4   │ 22 │
│ 5   │ 32 │
│ 6   │ 29 │
│ 7   │ 19 │
│ 8   │ 35 │
│ 9   │ 20 │
│ 10  │ 45 │
```

any idea? relatedly: how do you develop the package? I find I often have to start a new session because neither `include("src/Query.jl")` (for example), nor `reload("Query")` seems to update the macro definitions for me, or at least that's my interpretation. thanks for any help.

### CODE REVIEW

**Comment by floswald** [comment]
also, not sure where you'll want to merge that eventually, the `simple-map-syntax` branch was the one I branched off, that's why I chose this here.

**Comment by floswald** [comment]
@davidanthoff any idea about this issue with the module?

**Comment by davidanthoff** [comment]
Sorry, I got side-tracked with a couple other projects, and it will probably be a couple more days before I have time to look into this (no trivial explanation comes to mind).

**Comment by floswald** [comment]
no worries. i probably would just need to to know how you develop the package. terminal? inside `~/.julia/v0.6/Query` as a branch? Juno?

**Comment by davidanthoff** [comment]
Hm, I just tried this branch, and I can just run ``QueryPerf.run_benches()`` without an error... Are you sure you are on the latest version of things like IterableTables.jl?

I basically kill my julia process whenever I make a change to Query.jl, start a new REPL and execute some test code in there... I know there must be a better way, but hey, I'm too old to learn new tricks ;)

**Comment by davidanthoff** [comment]
I just merged the ``a..b`` branch, maybe you could change this PR so that it would merge into ``master``?

**Comment by floswald** [comment]
there is a more recent version of this PR now. #154

**Pull request closed without merging**
